### ISSUE TITLE
How to convert the predicted map to a binary image for evaluation?

### ISSUE THREAD

**Issue by ShuhanChen** [xw-hu/DSC#1]
I found the predicted shadow map is an intensity image, how to convert it to a binary image for evaluation?  Just set a global threshold, e.g., 0?

**Comment by xw-hu** [comment]
We apply CRF as the post-processing in testing. The predicted map after CRF is the binary map. You can find the link of the code in README/Test.

**Comment by ShuhanChen** [comment]
I downloaded your result maps, and found that there are still some pixel values between 0~255, e.g. 624.jpg. So I can't get the same accuracy and BER value as listed in your paper. Can you share the evaluation code?
In fig.5 of your paper, the last three columns also seem like intensity maps.
Thanks for your quick reply.

**Comment by xw-hu** [comment]
Maybe some images I forgot to apply the CRF. Anyway, the results should be similar. Please give me your email and I send you the evaluation code.

**Comment by ShuhanChen** [comment]
c.shuhan@gmail.com
thanks very much

**Comment by quanlzheng** [comment]
Dear Xiaowei,

I am interested in your work. I test your results but found the results have some difference in your paper, could you share the evaluation code with me for better evaluation?

My email is xiaolong921001@gmail.com

Thanks very much
