### ISSUE TITLE
NO model named DSC_iter_160000_lab.caffemodel is found

### ISSUE THREAD

**Issue by LR32768** [xw-hu/DSC#10]
Hello, I am interested in your work about shadow removing and I have an issue. In the file examples/DSC/test_removal.m, there is an assertion for the existence of the file 'snapshot/DSC_iter_160000_lab.caffemodel'. I guess it is the model trained by your lab to remove the shadow, however I can't find it anywhere or find any access to it in your description file README.md, so could you please tell where can I find it? Thanks a lot

**Comment by xw-hu** [comment]
"lab" means we trained the model in LAB color space. You can follow the paper to train the model by yourself.
