### ISSUE TITLE
irnn-layer missing

### ISSUE THREAD

**Issue by pascscho** [xw-hu/DSC#12]
I am trying to run the shadow detection but when inferring the net in python an error occurs. The error occurs at `net.forward()`. I compiled the CF-Caffe and no error occured during the compilation.

error looks like following:
`F0326 13:43:25.415571 15771 irnn_layer-cpp:73] Not Implemented Yet`
`*** Check failure stack trace: ***`
`Aborted (core dumped)`

Does someone have an idea how to solve this problem?

Thank you in advance!

**Comment by xw-hu** [comment]
Please run the code on GPU, since I didn't implement the CPU version of "irnn" layer. (Not Implemented Yet)

**Comment by pascscho** [comment]
Ok. I'll try it using the GPU. Thank you
