### ISSUE TITLE
Which part reflect 'Direction-aware attention mechanism' in the code?

### ISSUE THREAD

**Issue by f5556666** [xw-hu/DSC#13]
Hello, Mr. Hu
I hope to introduce it  'Direction-aware attention mechanism' into my experiment.I hope you can tell me where it is in the code.Is it in the DSC/examples/DSC/DSC_detection/DSC.prototxt?
Also, I would like to ask whether DSC module can be used in other parts besides focusing on the shadow part. For example, in high exposure areas, if possible, which parameters determine?
I look forward to your reply. Thank you.

**Comment by xw-hu** [comment]
Yes. It is in DSC.prototxt. But you also need the implementation functions of IRNN module, which is in the CF-Caffe. I think if you have learned how to use Caffe, it is easy to find and use the source code.
You are able to use it on other tasks, and there are no specific parameters. Maybe you need a smaller learning rate to train the network; see solver.prototxt. 

Good luck!
