### ISSUE TITLE
Test file error

### ISSUE THREAD

**Issue by msiraj83** [xw-hu/DSC#6]
Hi, 
I have build the DSC according to your instruction and build successfully. but when i want to build the test I got the following error..
![channel_wise_lyer](https://user-images.githubusercontent.com/8863047/43705655-55cebdee-998d-11e8-9cf8-8e869d0a1b62.png)

Can you help in this regard.

Thanks

**Comment by xw-hu** [comment]
Don't need "make test". Just run!
