### ISSUE TITLE
Error in Running the Testing Code in Matlab as well python

### ISSUE THREAD

**Issue by msiraj83** [xw-hu/DSC#7]
Hi,
I download the your trained model from the google drive and save it into models folder in the DSC root folder.  Change the required paths in matlab code for depoly and model files and try to run the code in matlab but i got the following error. Can you help me in this regards,
![matlab_error](https://user-images.githubusercontent.com/8863047/43755153-cf472dcc-9a38-11e8-9672-56aaef35c780.png)

After this i try to run the python Code and write it into python file as attached and than try to run the code but this time i got the following error. 
![python_error](https://user-images.githubusercontent.com/8863047/43755204-0aa5e462-9a39-11e8-9b3d-2d97dfc053af.png)

Help me how to run the testing code for detection.

**Comment by xw-hu** [comment]
please "make matcaffe" and "make pycaffe". See the installation instructions on the Caffe website.
