### ISSUE TITLE
Shadow removal results without the pre-trained filters

### ISSUE THREAD

**Issue by lmhieu612** [xw-hu/DSC#8]
Hi, it's a not an issue. I am just curious about the shadow removal results when your networks are trained from scratch.

**Comment by xw-hu** [comment]
We use the VGG network trained on ImageNet to initial the parameters.

**Comment by lmhieu612** [comment]
Hi, thank you for the prompt reply. I understand that from the paper as well. I am just curious about its impact, i.e., what is the performance of the model if it doesn't get initialized from the VGG pre-trained parameters.

**Comment by xw-hu** [comment]
You can have a try. I think it needs more training iterations.
